
* Nome do Software (ou Biblioteca):
- SIMULADOR DE ESTIMATIVA DE RESERVA DE RESERVATÓRIO UTILIZANDO EBM, COM ENFOQUE NOS RESERVATÓRIOS DE GÁS
- ProjetoEngenharia-SimuladorDeEstimativaDeReservaUtilizandoEBM-EnfoqueReservatoriosGas


* Resumo e/ou informação extra: 
- Desenvolver uma solução para determinar o volume original de fluido (principalmente gás) no reservatório.
- Selecionar o tipo de fluido presente no reservatório (gás).
– Selecionar o mecanismo de produção.
– Quando houver influxo de água, escolher o modelo que será utilizado para o cálculo deste influxo.

* Versão: 
- 2.0.

* Data:
- 2014/2 - segundo semestre.
  
* Autor de Contato:
- André Duarte Bueno <andreduartebueno@gmail.com>

* Lista dos Autores:
- JALILE BARTOLE PEREIRA - 2014 - V2
- THAÍSA DE CASTRO ALEIXO - 2014 - V2
- LEONARDO MESQUITA CAETANO - 2012 - V1
- THIAGO PESSANHA DE MACEDO - 2012 - V1
- André Duarte Bueno <andreduartebueno@gmail.com>

* Áreas de pesquisa vinculadas: 
- Modelagem Matemática Computacional
- Engenharia de Reservatório  

* Vinculo com: 
- Trabalho da disciplina de programação prática.

* Paradigmas: 
- POO - Programação Orientada a Objeto (códigos em C++)

* Tipo de Interface: 
- Terminal e gráfica (gnuplot).

* Plataformas Suportadas: 
- Windows e GNU/Linux e Mac OS X (não testada).

* Linguagens Utilizadas: 
- C++ 11.

* Bibliotecas Utilizadas (dependências):
- CGnuplot - https://github.com/ldsc/CGnuplot

* Softwares utilizados (dependências)
- gnuplot http://www.gnuplot.info/

* Tipo de Licença:
- GPL
- Entre em contato com o Prof. André Duarte Bueno
  andreduartebueno@gmail.com
  para que o mesmo gere um novo projeto no github do ldsc para que você (e sua equipe) possam trabalhar na nova versão.
- Se este projeto tem como número de versão 1.0 a nova versão deverá ser 2.0 e assim sucessivamente.
- Os nomes dos autores originais deve ser preservada na nova versão, ou seja, adicione a informação do número da versão, os nomes dos membros da nova equipe, mas jamais apague os nomes dos autores originais (isto seria plágio).
- Na descrição do projeto informe que trata-se de uma nova versão, que tem como base a versão anterior e DESTAQUE COM CLAREZA E OBJETIVIDADE QUAIS AS NOVIDADES DA NOVA VERSÃO.
  
* Links:

